name: Markdown Link Check
on:
  push:
    branches:
      - '*'
  pull_request:
  schedule:
    - cron: '0 7 * * *'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
