name: Semgrep
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  semgrep:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
